demo1/demo1/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include

urlpatterns = [
    path('admin/', admin.site.urls),
    url('task/',include('task.urls',namespace="task")),
    url("vote/",include("vote.urls",namespace="vote")),
]

demo1/task/urls.py
from django.conf.urls import url
from . import views

app_name = "task"

urlpatterns = [
    url(r'^home/$', views.home,name="home"),
    url(r"^list/$",views.list,name="list"),
    url(r"^detail/(\d+)/$",views.detail,name="detail"),
    url(r"^delete/(\d+)/$",views.delete,name="delete"),
    url(r"^addrole/(\d+)/$",views.addrole,name="addrole"),
    url(r"^addrolehand$",views.addrolehand,name="addrolehand"),
]

demo1/vote/urls.py
from django.conf.urls import url
from . import views

app_name = "vote"

urlpatterns = [
    url(r"^home/$",views.home,name="home"),
    url(r"^list/$",views.qlist,name="list"),
    url(r"^choice/(\d+)/$",views.choice,name="choice"),
    url(r"^count/$",views.count,name="count"),
    url(r"^counts/(\d+)/$",views.counts,name="counts"),
]

demo1/task/models.py
from django.db import models

# Create your models here.

class BookInfo(models.Model):
    btitle = models.CharField(max_length=20)
    bpub_data = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.btitle

class RoleInfo(models.Model):
    rname = models.CharField(max_length=20)
    rgender = models.BooleanField()
    rcontent = models.CharField(max_length=50)
    rbook = models.ForeignKey("BookInfo",on_delete=models.CASCADE)
    def __str__(self):
        return self.rname

demo1/vote/models.py
from django.db import models

# Create your models here.

class Questions(models.Model):
    qcontent = models.CharField(max_length=100)
    qpub_date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.qcontent
    def Qcontent(self):
        return self.qcontent
    Qcontent.short_description = "问题"
    def Qpub_date(self):
        return self.qpub_date
    Qpub_date.short_description = "提出时间"

class Answers(models.Model):
    acontent = models.CharField(max_length=100)
    acount = models.IntegerField(max_length=100)
    aquestion = models.ForeignKey("Questions",on_delete=models.CASCADE)
    def __str__(self):
        return self.acontent
    def Acontent(self):
        return self.acontent
    Acontent.short_description = "回答"
    def Acount(self):
        return self.acount
    Acount.short_description = "计数"
    def Aquestion(self):
        return self.aquestion
    Aquestion.short_description = "问题"

demo1/task/views.py
from django.shortcuts import render

# Create your views here.

from django.http import HttpResponse,HttpResponseRedirect
from .models import BookInfo,RoleInfo
from django.template import loader

def home(request):
    hometem = loader.get_template("task/home.html")
    cont = {"username":"王祖贤"}
    result = hometem.render(cont)
    return HttpResponse(result)

def list(request):
    bl = BookInfo.objects.all()
    cont = {"booklist":bl}
    return render(request,"task/list.html",cont)

def detail(request,id):
    try:
        book = BookInfo.objects.get(pk = int(id))
        return render(request, "task/detail.html",{"book":book})
    except:
        return HttpResponse("输入有误")

def delete(request,id):
    try:
        BookInfo.objects.get(pk = id).delete()
        bl = BookInfo.objects.all()
        return HttpResponseRedirect("/task/list/",{"booklist":bl})
    except:
        return HttpResponse("输入有误")

def addrole(request,bookid):
    return render(request,"task/addrole.html",{"bookid":bookid})

def addrolehand(request):
    rname = request.POST["rname"]
    rgender = request.POST["rgender"]
    rcontent = request.POST["rcontent"]
    rbook = request.POST["bookid"]
    b = BookInfo.objects.get(pk = rbook)
    r = RoleInfo()
    r.rname = rname
    if rgender == "0":
        r.rgender = False
    else:
        r.rgender = True
    r.rcontent = rcontent
    r.rbook = b
    r.save()
    return HttpResponseRedirect("/task/detail/%s/"%(rbook),{"book":b})

demo1/vote/views.py
from django.shortcuts import render

# Create your views here.

from django.http import HttpResponse,HttpResponseRedirect
from django.template import loader
from .models import Questions,Answers

def home(request):
    h = {"username":"梅艳芳"}
    return render(request,"vote/home.html",h)

def qlist(request):
    ql = Questions.objects.all()
    return render(request,"vote/qlist.html",{"questionlist":ql})

def choice(request,id):
    q = Questions.objects.get(pk = id)
    al = q.answers_set.all()
    return render(request,"vote/choice.html",{"answerlist":al,"question":q.qcontent})

def counts(request,id):
    qu = Questions.objects.get(pk = id)
    anl = qu.answers_set.all()
    qc = qu.qcontent
    return render(request, "vote/counts.html", {"answerlist": anl, "question": qc})

def count(request):
    an = request.POST["ch"]
    an = Answers.objects.get(pk = an)
    an.acount += 1
    an.save()
    qu = an.aquestion
    anl = qu.answers_set.all()
    qc = qu.qcontent
    # return HttpResponseRedirect("/vote/home/")
    # counttem = loader.get_template("vote/count.html")
    # result = counttem.render({"answerlist":anl,"question":qc})
    # return HttpResponse(result)
    # return render(request,"vote/count.html")
    # return render(request,"vote/counts.html",{"answerlist":anl,"question":qc})
    return HttpResponseRedirect("/vote/counts/%s/"%(qu.id),{"answerlist":anl,"question":qc})



# def counts(request):
#     qu = Questions.objects.all()

    # an = []
    # for i in qu:
    #     ans = i.answers_set.all()
    #     an.append(ans)
    # return render(request,"vote/count.html",{"questionlist":qu})

demo1/templates/task/addrole.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="/static/css/main.css">
</head>
<body>
    <div class="content">
        <h2>添加角色</h2>
        <br>
        <form action="{% url 'task:addrolehand'%}" method="post">
            <label for="rname">name:</label>
            <input type="text" name="rname"><br>
            <label for="rgender">gender:</label><br>
            <input type="radio" name="rgender" value="0">female <br>
            <input type="radio" name="rgender" value="1">male <br>
            <label for="rcontent">clan:</label>
            <input type="text" name="rcontent"><br>
            <input type="hidden" name="bookid" value="{{bookid}}">
            <input type="submit" value="添加">
        </form>
    </div>
</body>
</html>

demo1/templates/task/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>详情页</title>
    <link rel="stylesheet" href="/static/css/main.css">
</head>
<body>
    <div class="content">
        <h1>书名：{{book.btitle}}</h1>
        <ul>
            {% for role in book.roleinfo_set.all %}
                <li>{{role.rname}}----{{role.rcontent}}</li>
            {% empty %}
                <h3>no users</h3>
            {% endfor %}
        </ul>
        <br>
        <a href="{% url 'task:addrole' book.id%}">添加角色</a>

        {#<a href="/task/list/">返回列表页</a>#}
        <a href="{% url 'task:list' %}">返回列表页</a>
    </div>
</body>
</html>

demo1/templates/task/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>
    <link rel="stylesheet" href="/static/css/main.css">
</head>
<body>
    <div class="content">
        {% if username %}
        <h1>hello:{{username}}</h1>
        {% else %}
            <h1>no user</h1>
        {% endif %}
        <br>
        <img src="/static/imgs/1.png" alt="图片走丢了" width="1000px" >
        <br>
        {#<a href="/task/list">进入列表页</a>#}
        <a href="{% url 'task:list' %}">进入列表页</a>
    </div>
</body>
</html>

demo1/templates/task/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>列表页</title>
    <link rel="stylesheet" href="/static/css/main.css">
</head>
<body>
    <div class="content">
        <h1>书目</h1>
        <ul>
            {% for book in booklist %}
                {#<li><a href="/task/detail/{{book.id}}">{{book.btitle}}</a></li>#}
                <li><a href="{% url 'task:detail' book.id %}">{{book.btitle}}</a><a href="{% url 'task:delete' book.id %}">删除</a></li>
            {% empty %}
                <h3>书目为空</h3>
            {% endfor %}
        </ul>
        <br>
        {#<a href="/task/home">返回首页</a>#}
        <a href="{% url 'task:home' %}">返回首页</a>
    </div>
</body>
</html>

demo1/templates/vote/choice.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>命运石之门</title>
    <link rel="stylesheet" href="/static/css/main.css">
</head>
<body>
    <div class="content">
        <h1>{{question}}</h1>
        <form action="{% url 'vote:count' %}" method="post">
            <label for="ch">选择：</label>
            <br>
            {% for an in answerlist %}
                <input type="radio" name="ch" value="{{an.id}}">{{an}}<br>
            {% empty %}
                <h3>no choice</h3>
            {% endfor %}
            <input type="submit" value="提交">
        </form>
    </div>
</body>
</html>

demo1/templates/vote/count.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>计数</title>
    <link rel="stylesheet" href="/static/css/main.css">
</head>
<body>
    <div class="content">
        <!--<h1>问题列表</h1>-->
        <!--<ul>-->
            <!--{% for question in questionlist %}-->
                <!--<li><a href="{% url 'vote:choice' question.id %}">{{question.qcontent}}</a></li>-->
            <!--{% empty %}-->
                <!--<h3>no question</h3>-->
            <!--{% endfor %}-->
        <!--</ul>-->
        <!--<br>-->
        <!--<a href="{% url 'vote:home' %}">返回首页</a>-->




        <h1>{{question}}</h1>
        <ul>
            {% for an in answerlist %}
                <li>{{an.acontent}}----{{an.acount}}</li>
        </ul>
        <br>
        <a href="{% url 'vote:list' %}">返回问题列表</a>

    </div>
</body>
</html>

demo1/templates/vote/counts.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>详情</title>
    <link rel="stylesheet" href="/static/css/main.css">
</head>
<body>
    <div class="content">
        <h1>{{question}}</h1>
    <ul>
        {% for an in answerlist %}
            <li>{{an.acontent}}----{{an.acount}}</li>
        {% endfor %}
    </ul>
    <br>
    <a href="{% url 'vote:list' %}">返回问题列表</a>
    </div>
</body>
</html>

demo1/templates/vote/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>
    <link rel="stylesheet" href="/static/css/main.css">
</head>
<body>
    <div class="content">
        {% if username %}
            <h1>hello:{{username}}</h1>
        {% else %}
            <h1>no user</h1>
        {% endif %}
        <br>
        <img src="/static/imgs/1.png" alt="图片走丢了" width="1000px">
        <br>
        <a href="{% url 'vote:list' %}">列表页</a>
    </div>
</body>
</html>

demo1/templates/vote/qlist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>问题列表</title>
    <link rel="stylesheet" href="/static/css/main.css">
</head>
<body>
    <div class="content">
        <h1>问题列表</h1>
        <ul>
            {% for question in questionlist %}
                <li><a href="{% url 'vote:choice' question.id %}">{{question.qcontent}}</a></li>
            {% empty %}
                <h3>no question</h3>
            {% endfor %}
        </ul>
        <br>
        <a href="{% url 'vote:home' %}">返回首页</a>

    </div>
</body>
</html>